### ISSUE TITLE
missing custom fields not recognized

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#1]
@eddycolloton running the script on JPC_AV_00011_mediainfo.txt, which is made from a file that has none of the custom fields, and the script is telling me `All specified fields and values found in the MediaInfo output.`

script `creates a list of fields to check, but only to check that the fiels is not empty` but can it also give warning if the fields are not there at all?

**Comment by BleakleyMcD** [comment]
[JPC_AV_00011_mediainfo.txt](https://github.com/BleakleyMcD/JPC_AV/files/13398997/JPC_AV_00011_mediainfo.txt)

**Comment by eddycolloton** [comment]
Good catch, thanks! Script now checks if those fields exist. commit here: https://github.com/BleakleyMcD/JPC_AV/commit/6b4b605f4a2f33b42828a751a91737f0d77533a6

@BleakleyMcD This mediainfo has some other values that are different from the "JPCspecs_mi.txt" that I've been working of of:
Video: Pixel aspect ratio
Expected: 0.900
Actual: 0.909

Video: Frame rate
Expected: 29.970 (30000/1001) FPS
Actual: 29.970 (29970/1000) FPS

Video: Scan type
Expected: Interlaced
Actual: Progressive

Audio: Format
Expected: FLAC
Actual: PCM

The FPS thing is fucking weird, I'll see if I can have it check that differently or something. The other differences are more substantial though. Aside from the FPS check, should the conformance check allow for these different values?

**Comment by BleakleyMcD** [comment]
@eddycolloton thanks! I'll check it.

Hmmm. I transcoded that file from an uncompressed .mov and that may be the problem. I'll have to check. 

The FPS thing is indeed weird. Audio format should be PCM. Sorry if I listed it otherwise before.

**Comment by eddycolloton** [comment]
I can find a fix for fps thing, as long as it says 29.97 I don't think we really care about the fraction. 

I'll change expected audio codec value to PCM. Just want to confirm since FLAC is in all the specs.txt files and in target specs on confluence as well.

**Comment by BleakleyMcD** [comment]
Cab you make it accept both?

**Comment by eddycolloton** [comment]
Yup! We can do that, I'll need to tinker with it a bit, but should be possible.

**Comment by BleakleyMcD** [comment]
@eddycolloton been checking some files and haven't run into that pixel aspect ratio issue again. I think I deleted that file so I can't even see why it had .909  oh well!

```
/Users/bleakley/github/JPC_AV/JPC_AV_videoQC
≈:≈ python3 mediainfo_check.py /Users/bleakley/Dropbox\ \(Smithsonian\)/00_UtilitySan/2012_79__BOWSER/2012_79_2_49_1a_Positively_Black_TV_Segment/2012_79_2_49_1a_PM.mkv.mediainfo.txt
Some specified fields or values are missing or don't match:
Audio: Writing library
Expected: Lavc59.37.100 flac
Actual: Lavc59.18.100 flac

metadata field in General: Title does not exist
metadata field in General: Encoded by does not exist
metadata field in General: Description does not exist
metadata field in General: Encoding settings does not exist
metadata field in General: ORIGINAL MEDIA TYPE does not exist
                                                                                                                                                                              
/Users/bleakley/github/JPC_AV/JPC_AV_videoQC
≈:≈ 
```

One thing that did throw an error was a very small different in the writing library for the FLAC. I'm thinking checking for super specific writing libraries for either audio or video is probably way too strict. Thoughts?

**Comment by eddycolloton** [comment]
scripts now accept both flac and pcm for 'Audio: Format', will accept any fps value that begins with 29.97, and no longer checks writing libraries. Closing this issue.
