### ISSUE TITLE
feature reqeust: directory for QC generated metadata files

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#13]
1. have script create a directory called "qc_metadata" in the same directory as the .mkv file.
2. move all files created by `process_file.py` into this directory at the end of the script.
3. have script write to stdout that this has happened.

**Comment by eddycolloton** [comment]
I've added the directory as 'video_file_name'_qc_metadata. Is that ok or would you rather have it as just 'qc_metadata' for every file?

**Comment by BleakleyMcD** [comment]
sounds good your way!

**Comment by BleakleyMcD** [comment]
could you also have the script make one called "'video_file_name'_vrecord_metadata" and have the script move the following vrecord generated files into that? Namely:

- JPC_AV_01567_QC_output_graphs.jpeg
- JPC_AV_01567_vrecord_input.log
- JPC_AV_01567.mkv.qctools.mkv
- JPC_AV_01567.framemd5

**Comment by eddycolloton** [comment]
vrecord metadata directory added: https://github.com/JPC-AV/JPC_AV_videoQC/commit/d2af65c5865c67b45fa9950e42deea67fad498c7

**Comment by eddycolloton** [comment]
Of course! I've added files matching this pattern "_capture_options.log" to the move_vrec_files function.
