### ISSUE TITLE
feature request: batch processing

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#17]
Currently to run process_file.py on multiple files we need to do ``` python process_file.py --profile step1 FILE1.mkv && python process_file.py --profile step1 FILE2.mkv``` etc. 

Would like to run it as ```python process_file.py --profile step1 FILE1.mkv FILE2.mkv FILE3.mkv``` etc.

Even better - run it on the directories containing the .mkv - 

```python process_file.py --profile step1 JPC_AV_00001 JPC_AV_00002 JPC_AV_0003``` where JPC_AV_##### is the directory

**Comment by eddycolloton** [comment]
process_file.py can now take directories as input if the "-d" flag is used:
python process_file.py -d --profile step2 [some_directory] [some_other_directory]
https://github.com/JPC-AV/JPC_AV_videoQC/commit/a6a7eb41e9a0743ff279a9da2d187766ebaf4d4d

Can also take multiple files with either "-f" flag, or without flag at all.

Test multiple inputs when you can, let me know about logging and output. Initial tests working well!

Would you like directories to be the default input instead? process_file.py could still take files as input but would require -f flag. This would make -d flag for directories optional.

**Comment by BleakleyMcD** [comment]
@eddycolloton sweeeet. We will check today. Directories as default with -f needed for multiple files would be great. 

@DSohl can you make some test directories (maybe just copy a few completed tape directories into a test area?) and run some tests?

**Comment by DSohl** [comment]
I've done two tests now on one of the computers here, and the results are very promising. I'll try again before I leave on the tapes I digitized today - ie, new files that haven't had any QC done.

I encountered some issues during my trial on the other computer which I'm tempted to chalk up to human error. Also noteworthy. Will update if I can't get that working by EOD.

**Comment by eddycolloton** [comment]
As of most recent commit, directories are default expected input, and the -f flag is required for processing file. https://github.com/JPC-AV/JPC_AV_videoQC/commits/main/

Kind of makes the name of the script obsolete though. Any ideas what we should call it? JPChecker? JPC-QC? A-V Spex?
