### ISSUE TITLE
rename directory JPC_AV to processing_scripts or something similar

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#18]
open to suggestions. didn't want to jump in there and change it.

**Comment by eddycolloton** [comment]
Hi @BleakleyMcD @DSohl - I've reorganized the repo a little bit. process_file.py is now process_av.py. It's now at the top level of a directory, and the other scripts are in 2 subdirectories: utils and checks. 

I also changed the name of the JPC_AV directory to my proposed name for the python project, "AV_Spex" which is inspired by the 70s punk band X-Ray Spex.

**Comment by BleakleyMcD** [comment]
love it!
