### ISSUE TITLE
feature request: video access file creation

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#19]
Have process_file.py profile 1 create a .mp4 access file of the .mkv named the same as the .mkv appended with _access

something akin to : `ffmpeg -n -vsync 0 -nostdin -v info -hide_banner -stats -i "${INPUT}" -movflags faststart -map 0:v -map 0:a'?' -c:v libx264 -vf "yadif=1,format=yuv420p" -crf 18 -preset fast -maxrate 1000k -bufsize 1835k -c:a aac -strict -2 -b:a 192k -f mp4 "${INPUT_access}.mp4`

place the file next to the .mkv

**Comment by eddycolloton** [comment]
I have this working! In command_config.yaml, need to set [outputs][access_file] to 'yes', and process_file.py will create an access file after making the qctools report. Should this be part of step or step2?

**Comment by BleakleyMcD** [comment]
@eddycolloton cool cool! step1, please.

**Comment by eddycolloton** [comment]
Ok! access file added to step1 profile. If step2 profile is run, access file will not be made.
 https://github.com/JPC-AV/JPC_AV_videoQC/commit/71c31a5df440b85808bda40f19ce81ac76505859

**Comment by BleakleyMcD** [comment]
yay!
