### ISSUE TITLE
Feature request: processing time output && ascii indicator

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#21]
After  `Processing of JPC_AV_xxxxx complete. Output files saved in the directory: <path to file directory>`

add the following:
`Process time for JPC_AV_xxxxx: time start: yyyy-dd-mm hh:mm:ss ; time end: yyyy-dd-mm hh:mm:ss ; total time: hh:mm:ss`

For clarity of output, when processing multiple directories, indicate in stdout where a new files process starts with some sorts of substantial ascii e.g.:

^
^^
^^^
^^^^
^^^^^
^^^^
^^^
^^
^

This could come right after the process time asked for above and before `Input video file found: <path to .mkv file>`

**Comment by eddycolloton** [comment]
Hi Blake, I've added processing time output and I've added a little ascii art at the beginning and end of processing a file to hopefully breakup the output a bit. 
I'm using a ascii art python module, so after you grab most recent commit, also run ` pip install -r requirements.txt` 

https://github.com/JPC-AV/JPC_AV_videoQC/commit/882859957163fa5348d11695e61885eb17573bf7

**Comment by BleakleyMcD** [comment]
![image](https://github.com/JPC-AV/JPC_AV_videoQC/assets/5872785/e1775a7b-f23c-4834-969a-b89b29cdaf0f)

💓💓💓
