### ISSUE TITLE
qcli location 

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#28]
```
running command: qcli -i "/Volumes/JPCARCHIVE/00_fromDMZ/upload/DCvideo/JPC_AV_00008/JPC_AV_00008.mkv" -o /Volumes/JPCARCHIVE/00_fromDMZ/upload/DCvideo/JPC_AV_00008/JPC_AV_00008_qc_metadata/JPC_AV_00008.qctools.xml.gz
/bin/sh: qcli: command not found
```

```
/Users/medialab/github/jpc_av/videoqc_jpc_av/AV_Spex
≈:≈ which qcli
/usr/local/bin/qcli
```

**Comment by eddycolloton** [comment]
This is a weird one. My qcli is in the homebrew folder but python was able to find it. I have tried explicitly adding PATH to the env in the function that runs cli commands, maybe that will help? https://github.com/JPC-AV/JPC_AV_videoQC/commit/f1370c8d159181388ee819db92d489d47b1d29d7
