### ISSUE TITLE
qctools progress

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#29]
Newest version of script seems to have lost the progress tracking for the qctools report creation. @eddycolloton

**Comment by eddycolloton** [comment]
I'm not able to recreate this error locally. You're getting "Running command: qcli -i [some file] -o [some file.qctools.xml.gs]"? 
Have the scripts run on this machine before? Does running qcli on its own work?

**Comment by BleakleyMcD** [comment]
```
running command: qcli -i "/Volumes/JPCARCHIVE/00_fromDMZ/upload/DCvideo/JPC_AV_00011/JPC_AV_00011.mkv" -o /Volumes/JPCARCHIVE/00_fromDMZ/upload/DCvideo/JPC_AV_00011/JPC_AV_00011_qc_metadata/JPC_AV_00011.qctools.xml.gz
qcli dev build, Nov 29 2023 03:09:40
filters selected: signalstats psnr astats 

analyzing input file... /Volumes/JPCARCHIVE/00_fromDMZ/upload/DCvideo/JPC_AV_00011/JPC_AV_00011.mkv
.................................................. 100 of 100 %
analyzing completed

generating QCTools report... 
.................................................. 100 of 100 %
generating QCTools report... done, in /Volumes/JPCARCHIVE/00_fromDMZ/upload/DCvideo/JPC_AV_00011/JPC_AV_00011_qc_metadata/JPC_AV_00011.qctools.xml.gz

Please note that any warnings on metadata are just used to help any issues with your file. If they are not relevant at this point in your workflow, just ignore this. Thanks!

Processing complete:
```

Not sure why the QCT progress report shows twise. regardless, there was no movement on the progress bar, it stayed at zero for along time and then went to 100 as the file finished.

**Comment by eddycolloton** [comment]
I have JPC_AV_00011 here locally so I'll do some tests. 
Just running qcli -i on JPC_AV_00011 by itself (without python) and it's sitting at zero for a long time... 
I'll have to leave it for the night and see if I get the same output.

QCTools progress output comes directly from qcli application. I only do the progress calculation in python for  stream hash, whole file md5, and access copy.

**Comment by eddycolloton** [comment]
I get very similar output:

```
Running command: qcli -i "/Users/eddycolloton/git/JPC_AV/JPC_AV_videoQC/sample_files/JPC_AV_00011/JPC_AV_00011.mkv" -o /Users/eddycolloton/git/JPC_AV/JPC_AV_videoQC/sample_files/JPC_AV_00011/JPC_AV_00011_qc_metadata/JPC_AV_00011.qctools.xml.gz
qcli dev build, Oct 12 2023 07:09:34
filters selected: signalstats psnr astats 

analyzing input file... /Users/eddycolloton/git/JPC_AV/JPC_AV_videoQC/sample_files/JPC_AV_00011/JPC_AV_00011.mkv
.................................................. 100 of 100 %
analyzing completed

generating QCTools report... 
.................................................. 100 of 100 %
generating QCTools report... done, in /Users/eddycolloton/git/JPC_AV/JPC_AV_videoQC/sample_files/JPC_AV_00011/JPC_AV_00011_qc_metadata/JPC_AV_00011.qctools.xml.gz
```

The 1st progress bar is the "analysis" stage and the 2nd progress bar is for creating the report. I get basically the same results when running `qcli -i /Users/eddycolloton/git/JPC_AV/JPC_AV_videoQC/sample_files/JPC_AV_00011/JPC_AV_00011.mkv -o /Users/eddycolloton/git/JPC_AV/JPC_AV_videoQC/sample_files/JPC_AV_00011/JPC_AV_00011.qctools.xml.gz`

So I think bad progress reporting is a qctools thing and not an av spex thing. 

I thought this sounded familiar and turns out I have an open issue about the lack of feedback you get during analysis from ~1.5 years ago: https://github.com/bavc/qctools/issues/732#issue-1324752458

**Comment by eddycolloton** [comment]
Closing issue per discussion re: qctools
