### ISSUE TITLE
feature request: av-spex --help outputs version

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#41]
It would be helpful to have `av-spex --help` output the AV-Spex version. Seems like we are far enough into the project that versioning could begin being useful to resolve issues. Or if not version, something to indicate what status code being used is.

**Comment by eddycolloton** [comment]
Good call! av-spex --help and av-spex --version now output version number from the pyproject.toml. We're now at v 0.3.0 : https://github.com/JPC-AV/JPC_AV_videoQC/commits/main/
