### ISSUE TITLE
error: ModuleNotFoundError: No module named 'lxml'

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#45]
new install on computer. after `python -m pip install -e .` successful install ` av-spex --help` returned:
```
≈:≈ av-spex --help
Traceback (most recent call last):
  File "/opt/anaconda3/envs/JPC_AV/bin/av-spex", line 5, in <module>
    from AV_Spex.av_spex_the_file import main
  File "/Users/mcdowellb/github/jpc/videoqc_jpc_av/src/AV_Spex/av_spex_the_file.py", line 31, in <module>
    from .checks.qct_parse import run_qctparse
  File "/Users/mcdowellb/github/jpc/videoqc_jpc_av/src/AV_Spex/checks/qct_parse.py", line 11, in <module>
    from lxml import etree	
ModuleNotFoundError: No module named 'lxml'

```

fixed issued with `python -m pip install lxml`

**Comment by eddycolloton** [comment]
I had not added lxml to the dependencies list! `pip install` reads the list from the pyproject.toml file. I must have had the lxml module installed for something else without realizing it. 

It's now added to the list of dependencies so in the future pip install should install it if it is missing: https://github.com/JPC-AV/JPC_AV_videoQC/commit/a903c4cb8e8894680f448814c1dfc1259b0d36d8

**Comment by BleakleyMcD** [comment]
cool cool :)
